pragma Singleton
import QtQuick 2.0
 
QtObject {
    property string lightSystemAltHighColor: "#FFFFFFFF"
    property string lightSystemAltLowColor: "#33FFFFFF"
    property string lightSystemAltMediumColor: "#99FFFFFF"
    property string lightSystemAltMediumHighColor: "#CCFFFFFF"
    property string lightSystemAltMediumLowColor: "#66FFFFFF"
    property string lightSystemBaseHighColor: "#FF000000"
    property string lightSystemBaseLowColor: "#33000000"
    property string lightSystemBaseMediumColor: "#99000000"
    property string lightSystemBaseMediumHighColor: "#CC000000"
    property string lightSystemBaseMediumLowColor: "#66000000"
    property string lightSystemChromeAltLowColor: "#FF171717"
    property string lightSystemChromeBlackHighColor: "#FF000000"
    property string lightSystemChromeBlackLowColor: "#33000000"
    property string lightSystemChromeBlackMediumLowColor: "#66000000"
    property string lightSystemChromeBlackMediumColor: "#CC000000"
    property string lightSystemChromeDisabledHighColor: "#FFCCCCCC"
    property string lightSystemChromeDisabledLowColor: "#FF7A7A7A"
    property string lightSystemChromeHighColor: "#FFCCCCCC"
    property string lightSystemChromeLowColor: "#FFF2F2F2"
    property string lightSystemChromeMediumColor: "#FFE6E6E6"
    property string lightSystemChromeMediumLowColor: "#FFF2F2F2"
    property string lightSystemChromeWhiteColor: "#FFFFFFFF"
    property string lightSystemListLowColor: "#19000000"
    property string lightSystemListMediumColor: "#33000000"

    property string darkSystemAltHighColor: "#FF000000"
    property string darkSystemAltLowColor: "#33000000"
    property string darkSystemAltMediumColor: "#99000000"
    property string darkSystemAltMediumHighColor: "#CC000000"
    property string darkSystemAltMediumLowColor: "#66000000"
    property string darkSystemBaseHighColor: "#FFFFFFFF"
    property string darkSystemBaseLowColor: "#33FFFFFF"
    property string darkSystemBaseMediumColor: "#99FFFFFF"
    property string darkSystemBaseMediumHighColor: "#CCFFFFFF"
    property string darkSystemBaseMediumLowColor: "#66FFFFFF"
    property string darkSystemChromeAltLowColor: "#FFF2F2F2"
    property string darkSystemChromeBlackHighColor: "#FF000000"
    property string darkSystemChromeBlackLowColor: "#33000000"
    property string darkSystemChromeBlackMediumLowColor: "#66000000"
    property string darkSystemChromeBlackMediumColor: "#CC000000"
    property string darkSystemChromeDisabledHighColor: "#FF333333"
    property string darkSystemChromeDisabledLowColor: "#FF858585"
    property string darkSystemChromeHighColor: "#FF767676"
    property string darkSystemChromeLowColor: "#FF171717"
    property string darkSystemChromeMediumColor: "#FF1F1F1F"
    property string darkSystemChromeMediumLowColor: "#FF2B2B2B"
    property string darkSystemChromeWhiteColor: "#FFFFFFFF"
    property string darkSystemListLowColor: "#19FFFFFF"
    property string darkSystemListMediumColor: "#33FFFFFF"
}

